version: "3.9"

services:
  db:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - ${PORT_DB}:5432
    volumes:
      - postgresdb-data:/var/lib/postgresql/data

volumes:
  postgresdb-data:
